version: '3'

networks:
  TestServiceNetwork:
    ipam:
      config:
        - subnet: 192.168.213.0/24

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq
    hostname: rabbitmq
    networks: 
      TestServiceNetwork:
        ipv4_address: 192.168.213.10

